servers:
- host: local.just.here
  route: /*
  upstreams:
  - http://nginx1
  - http://nginx2
- host: local.notreal.xyz
  route: /*
  upstreams:
  - http://httpd
- host: localhost:8080
  route: /*
  upstreams:
  - http://nginx1
  - http://nginx2
- host: abc.localhost:8080
  route: /*
  upstreams:
  - http://httpd