servers:
- host: localhost:8080
  route: /api/*
  upstreams:
  - http://localhost:8083
  - http://localhost:8084
- host: localhost:8080
  route: /*
  upstreams:
  - http://localhost:8081
  - http://localhost:8082

